default:
  image: rust:latest
  cache: # Cache the following directories
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
  before_script:
    - rustc --version                               # Print version of Rust compiler

stages:
  - source
  - update dependencies
  - build
  - test
  - deploy

format-job:
  stage: source
  script:
    - rustup component add rustfmt
    - cargo fmt

fix-job:
  stage: source
  script:
    - cargo fix

lint-job:
  stage: source
  script:
    - rustup component add clippy
    - cargo clippy -- -Dwarnings

update-dependencies-job:
  stage: update dependencies
  script:
    - cargo update

build-job:
  stage: build
  script:
    - cargo install cargo-hack
    - cargo hack check --feature-powerset --mutually-exclusive-features no_std,uuid --lib --tests

test-job:
  stage: test
  allow_failure: false
  script:
    - cargo install cargo-hack
    - cargo hack test --feature-powerset --mutually-exclusive-features no_std,uuid

deploy:
  stage: deploy
  needs:
    - test-job
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - cargo publish --token $CARGO_REGISTRY_TOKEN
  release:
    name: $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    description: './CHANGELOG.md'
