default:
  image: rust:1.71.0

stages:
  - setup
  - source
  - build
  - test
  - deploy

setup-job:
  stage: setup
  script:
    - rustup component add clippy
    - cargo install cargo-hack

lint-job:
  stage: source
  needs:
    - setup-job
  script:
    - cargo clippy -- -Dwarnings

build-job:
  stage: build
  needs:
    - setup-job
  script:
    - cargo hack check --feature-powerset --mutually-exclusive-features no_std,uuid --lib --tests

test-job:
  stage: test
  allow_failure: false
  needs:
    - setup-job
  script:
    - cargo hack test --feature-powerset --mutually-exclusive-features no_std,uuid

deploy:
  stage: deploy
  needs:
    - test-job
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - cargo publish
  variables:
    CARGO_REGISTRY_TOKEN: $CARGO_REGISTRY_TOKEN
