name: Build

on:
  push:
  pull_request:

jobs:
  build-on-ubuntu-latest:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Cargo Hack Check
        run: cargo hack check --feature-powerset --mutually-exclusive-features no_std,uuid --lib --tests
      - name: Cargo Hack Test
        run: cargo hack test --feature-powerset --mutually-exclusive-features no_std,uuid
